const r=require('express').Router();
const ctrl=require('../controllers/deliveries.controller');
const scan=require('../controllers/scan.controller');
const {authenticate}=require('../middleware/auth');
const {createDelivery}=require('../validators/delivery.validator');
r.post('/',authenticate(['merchant']),createDelivery,ctrl.create);
r.get('/',authenticate(['merchant','admin']),ctrl.list);
r.get('/:id',authenticate(['merchant','driver','admin']),ctrl.get);
r.post('/:id/assign',authenticate(['admin']),ctrl.assignDriver);
r.post('/:id/scan-pickup',authenticate(['driver']),scan.scanPickup);
r.post('/:id/stops/:stopId/confirm',authenticate(['driver']),scan.confirmDelivery);
module.exports=r;
