const r=require('express').Router();
const ctrl=require('../controllers/drivers.controller');
const {authenticate}=require('../middleware/auth');
r.post('/register',ctrl.register);
r.post('/login',ctrl.login);
r.get('/me',authenticate(['driver']),ctrl.me);
r.patch('/location',authenticate(['driver']),ctrl.updateLocation);
r.get('/available',authenticate(['admin']),ctrl.listAvailable);
r.get('/:id',authenticate(['admin']),ctrl.getById);
module.exports=r;
