const r=require('express').Router();
const ctrl=require('../controllers/merchants.controller');
const {authenticate}=require('../middleware/auth');
r.get('/me',authenticate(['merchant']),ctrl.me);
r.patch('/me',authenticate(['merchant']),ctrl.update);
r.get('/me/deliveries',authenticate(['merchant']),ctrl.deliveries);
r.get('/me/stats',authenticate(['merchant']),ctrl.stats);
r.get('/:id',authenticate(['admin']),ctrl.getById);
r.get('/',authenticate(['admin']),ctrl.list);
module.exports=r;
